### ISSUE TITLE
Using environmentViewModel(_ viewModel) Causes App To Crash

### ISSUE THREAD

**Issue by KwabenBerko** [rickclephas/KMM-ViewModel#13]
When using the `environmentViewModel(_ viewModel: KMMViewModel)` function, the app crashes:

```swift
    ContentView()
        .environmentViewModel(viewModel)
```

Interesting, using the alternative `environmentViewModel(_ projectedValue: ObservableViewModel<KMMViewModel>.Projection)` works:

```swift
    ContentView()
        .environmentViewModel(_viewModel.projectedValue)
```

Great library by the way!

**Comment by rickclephas** [comment]
Thanks! At the moment this is expected behaviour. 
The summary is that Kotlin ViewModels can only be wrapped once. By using the `projectedValue` the wrapping is skipped, allowing you to forward an already wrapped ViewModel.
For more details see #11.

P.S. the following should also work (it's a little shorter):
```swift
.environmentViewModel($viewModel)
```
