### ISSUE TITLE
How to create a Binding for SwiftUI?

### ISSUE THREAD

**Issue by jnelle** [rickclephas/KMM-ViewModel#31]
Hey thanks for the great library! :)

I'm having issues with creating a Binding<Bool> Variable for SwiftUI. My KMM code is the following:

```kotlin
class CommonAuthViewModel : KMMViewModel(), KoinComponent {
    @NativeCoroutinesState
    var isLoggedIn: StateFlow<Boolean> =
        MutableStateFlow(viewModelScope, false)

    fun changeState() {
            isLoggedIn.value = true
        }
}
```

In XCode I faced the following error:
<img width="861" alt="image" src="https://github.com/rickclephas/KMM-ViewModel/assets/36324542/787ac6de-1864-457d-9267-95168a6f27ec">

In my view I initialized the ViewModel like the following:
```swift
    @StateViewModel var authViewModel = AuthViewModel()
```

I'm also confused from XCode it shows that this variable is a Binding<Bool>
<img width="735" alt="image" src="https://github.com/rickclephas/KMM-ViewModel/assets/36324542/72372660-2ac9-45a7-b030-a190dd861c4f">

I want to thank you for this library and also thanking for the good communication with the community, that is not a matter of course and I appreciate that very much!

**Comment by rickclephas** [comment]
Bindings are automatically provided for mutable properties.
In your case `isLoggedIn` is converted to a read-only property due to the `StateFlow` return type.
Changing the return type to `MutableStateFlow` will generate a mutable property.

Which will support bindings when combined with `@StateViewModel` (or one of the other property wrappers).

**Comment by jnelle** [comment]
Thanks, worked for me! :)
